/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zupedu.conta.conta;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NovaContaEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3541781037590218494L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NovaContaEvent\",\"namespace\":\"com.zupedu.conta.conta\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"agencia\",\"type\":\"int\"},{\"name\":\"numero\",\"type\":\"long\"},{\"name\":\"saldo\",\"type\":[{\"type\":\"string\",\"java-class\":\"java.math.BigDecimal\"}]}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NovaContaEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NovaContaEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NovaContaEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NovaContaEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NovaContaEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NovaContaEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NovaContaEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NovaContaEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NovaContaEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private int agencia;
  private long numero;
  private java.lang.Object saldo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NovaContaEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param agencia The new value for agencia
   * @param numero The new value for numero
   * @param saldo The new value for saldo
   */
  public NovaContaEvent(java.lang.Long id, java.lang.Integer agencia, java.lang.Long numero, java.lang.Object saldo) {
    this.id = id;
    this.agencia = agencia;
    this.numero = numero;
    this.saldo = saldo;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return agencia;
    case 2: return numero;
    case 3: return saldo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: agencia = (java.lang.Integer)value$; break;
    case 2: numero = (java.lang.Long)value$; break;
    case 3: saldo = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'agencia' field.
   * @return The value of the 'agencia' field.
   */
  public int getAgencia() {
    return agencia;
  }


  /**
   * Sets the value of the 'agencia' field.
   * @param value the value to set.
   */
  public void setAgencia(int value) {
    this.agencia = value;
  }

  /**
   * Gets the value of the 'numero' field.
   * @return The value of the 'numero' field.
   */
  public long getNumero() {
    return numero;
  }


  /**
   * Sets the value of the 'numero' field.
   * @param value the value to set.
   */
  public void setNumero(long value) {
    this.numero = value;
  }

  /**
   * Gets the value of the 'saldo' field.
   * @return The value of the 'saldo' field.
   */
  public java.lang.Object getSaldo() {
    return saldo;
  }


  /**
   * Sets the value of the 'saldo' field.
   * @param value the value to set.
   */
  public void setSaldo(java.lang.Object value) {
    this.saldo = value;
  }

  /**
   * Creates a new NovaContaEvent RecordBuilder.
   * @return A new NovaContaEvent RecordBuilder
   */
  public static com.zupedu.conta.conta.NovaContaEvent.Builder newBuilder() {
    return new com.zupedu.conta.conta.NovaContaEvent.Builder();
  }

  /**
   * Creates a new NovaContaEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NovaContaEvent RecordBuilder
   */
  public static com.zupedu.conta.conta.NovaContaEvent.Builder newBuilder(com.zupedu.conta.conta.NovaContaEvent.Builder other) {
    if (other == null) {
      return new com.zupedu.conta.conta.NovaContaEvent.Builder();
    } else {
      return new com.zupedu.conta.conta.NovaContaEvent.Builder(other);
    }
  }

  /**
   * Creates a new NovaContaEvent RecordBuilder by copying an existing NovaContaEvent instance.
   * @param other The existing instance to copy.
   * @return A new NovaContaEvent RecordBuilder
   */
  public static com.zupedu.conta.conta.NovaContaEvent.Builder newBuilder(com.zupedu.conta.conta.NovaContaEvent other) {
    if (other == null) {
      return new com.zupedu.conta.conta.NovaContaEvent.Builder();
    } else {
      return new com.zupedu.conta.conta.NovaContaEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for NovaContaEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NovaContaEvent>
    implements org.apache.avro.data.RecordBuilder<NovaContaEvent> {

    private long id;
    private int agencia;
    private long numero;
    private java.lang.Object saldo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zupedu.conta.conta.NovaContaEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.agencia)) {
        this.agencia = data().deepCopy(fields()[1].schema(), other.agencia);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.numero)) {
        this.numero = data().deepCopy(fields()[2].schema(), other.numero);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.saldo)) {
        this.saldo = data().deepCopy(fields()[3].schema(), other.saldo);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing NovaContaEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zupedu.conta.conta.NovaContaEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.agencia)) {
        this.agencia = data().deepCopy(fields()[1].schema(), other.agencia);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero)) {
        this.numero = data().deepCopy(fields()[2].schema(), other.numero);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.saldo)) {
        this.saldo = data().deepCopy(fields()[3].schema(), other.saldo);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'agencia' field.
      * @return The value.
      */
    public int getAgencia() {
      return agencia;
    }


    /**
      * Sets the value of the 'agencia' field.
      * @param value The value of 'agencia'.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder setAgencia(int value) {
      validate(fields()[1], value);
      this.agencia = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'agencia' field has been set.
      * @return True if the 'agencia' field has been set, false otherwise.
      */
    public boolean hasAgencia() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'agencia' field.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder clearAgencia() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero' field.
      * @return The value.
      */
    public long getNumero() {
      return numero;
    }


    /**
      * Sets the value of the 'numero' field.
      * @param value The value of 'numero'.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder setNumero(long value) {
      validate(fields()[2], value);
      this.numero = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numero' field has been set.
      * @return True if the 'numero' field has been set, false otherwise.
      */
    public boolean hasNumero() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numero' field.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder clearNumero() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'saldo' field.
      * @return The value.
      */
    public java.lang.Object getSaldo() {
      return saldo;
    }


    /**
      * Sets the value of the 'saldo' field.
      * @param value The value of 'saldo'.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder setSaldo(java.lang.Object value) {
      validate(fields()[3], value);
      this.saldo = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'saldo' field has been set.
      * @return True if the 'saldo' field has been set, false otherwise.
      */
    public boolean hasSaldo() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'saldo' field.
      * @return This builder.
      */
    public com.zupedu.conta.conta.NovaContaEvent.Builder clearSaldo() {
      saldo = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NovaContaEvent build() {
      try {
        NovaContaEvent record = new NovaContaEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.agencia = fieldSetFlags()[1] ? this.agencia : (java.lang.Integer) defaultValue(fields()[1]);
        record.numero = fieldSetFlags()[2] ? this.numero : (java.lang.Long) defaultValue(fields()[2]);
        record.saldo = fieldSetFlags()[3] ? this.saldo :  defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NovaContaEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<NovaContaEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NovaContaEvent>
    READER$ = (org.apache.avro.io.DatumReader<NovaContaEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










